/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.smartdoorlock.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param deviceName 
 * @param id 
 * @param status 
 */


data class DomainsLog (

    @SerializedName("device_name")
    val deviceName: kotlin.String,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("status")
    val status: kotlin.Boolean

) {


}

