/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.smartdoorlock.openapi.models

import id.my.smartdoorlock.openapi.models.DomainsLog

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param logs 
 */


data class GetAllLogsResponse (

    @SerializedName("logs")
    val logs: kotlin.collections.List<DomainsLog>

) {


}

