/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.smartdoorlock.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param slot 
 */


data class TriggerFingerprintModeRequest (

    @SerializedName("slot")
    val slot: kotlin.Int

) {


}

