/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.smartdoorlock.openapi.apis

import id.my.smartdoorlock.openapi.models.ChangePinRequest
import id.my.smartdoorlock.openapi.models.ChangePinResponse
import id.my.smartdoorlock.openapi.models.ValidatePinRequest
import id.my.smartdoorlock.openapi.models.ValidatePinResponse

import id.my.smartdoorlock.openapi.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import java.text.DateFormat

    open class ConfigurationApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    jsonBlock: GsonBuilder.() -> Unit = ApiClient.JSON_DEFAULT,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
        jsonBlock,
    ) {

        /**
        * PUT /api/v1/configuration/pin
        * 
        * 
         * @param request body 
         * @return ChangePinResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun changePin(request: ChangePinRequest): HttpResponse<ChangePinResponse> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = request

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/api/v1/configuration/pin",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /api/v1/configuration/pin
        * 
        * 
         * @param request body 
         * @return ValidatePinResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun validatePin(request: ValidatePinRequest): HttpResponse<ValidatePinResponse> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = request

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/configuration/pin",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
