/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package id.my.smartdoorlock.openapi.apis

import id.my.smartdoorlock.openapi.models.DeleteAllLogsResponse
import id.my.smartdoorlock.openapi.models.GetAllLogsResponse
import id.my.smartdoorlock.openapi.models.TriggerBuzzerAlarmResponse
import id.my.smartdoorlock.openapi.models.TriggerFingerprintModeRequest
import id.my.smartdoorlock.openapi.models.TriggerFingerprintModeResponse
import id.my.smartdoorlock.openapi.models.TriggerOpenDoorResponse
import id.my.smartdoorlock.openapi.models.TriggerRFIDModeRequest
import id.my.smartdoorlock.openapi.models.TriggerRFIDModeResponse

import id.my.smartdoorlock.openapi.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import java.text.DateFormat

    open class ControlApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    jsonBlock: GsonBuilder.() -> Unit = ApiClient.JSON_DEFAULT,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
        jsonBlock,
    ) {

        /**
        * DELETE /api/v1/control/logs
        * 
        * 
         * @return DeleteAllLogsResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun deleteAllLogs(): HttpResponse<DeleteAllLogsResponse> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/control/logs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /api/v1/control/logs
        * 
        * 
         * @return GetAllLogsResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun getAllLogs(): HttpResponse<GetAllLogsResponse> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/control/logs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /api/v1/control/buzzer-alarm
        * 
        * 
         * @return TriggerBuzzerAlarmResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun triggerBuzzerAlarm(): HttpResponse<TriggerBuzzerAlarmResponse> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/control/buzzer-alarm",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /api/v1/control/fingerprint-mode
        * 
        * 
         * @param body body 
         * @return TriggerFingerprintModeResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun triggerFingerprintMode(body: TriggerFingerprintModeRequest): HttpResponse<TriggerFingerprintModeResponse> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/control/fingerprint-mode",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /api/v1/control/open-door
        * 
        * 
         * @return TriggerOpenDoorResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun triggerOpenDoor(): HttpResponse<TriggerOpenDoorResponse> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/control/open-door",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /api/v1/control/rfid-mode
        * 
        * 
         * @param body body 
         * @return TriggerRFIDModeResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun triggerRFIDMode(body: TriggerRFIDModeRequest): HttpResponse<TriggerRFIDModeResponse> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/control/rfid-mode",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
